In [1]:
import sys
import numpy as np
import matplotlib

In [3]:
print("Python:",sys.version)
print("Numpy :",np.__version__)
print("Matplotlib:",matplotlib.__version__)

Python: 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
Numpy : 1.18.1
Matplotlib: 3.1.3


In [4]:
inputs=[1.2,5.1,2.1]
weights=[3.1,2.1,8.7]
bias=3

In [5]:
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

35.7


In [6]:
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

2.3


In [7]:
inputs=[1,2,3,4]
weights1=[0.2,0.8,-0.5,1.0]
weights2=[0.5,0.91,0.26,-0.5]
weights3=[0.26,-0.27,-0.17,0.87]
bias1=2
bias2=3
bias3=0.5
output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
print(output)

[6.3, 4.1000000000000005, 3.19]


In [8]:
weights=[[0.2,0.8,-0.5,1.0],[0.5,0.91,0.26,-0.5],[0.26,-0.27,-0.17,0.87]]
bias=[1,2,3,0.5]
inputs=[1,2,3]

In [9]:
layer=[]
for neuron_weights,neuron_bias in zip(weights,bias):
    neuron=0
    for n_input,weight in zip(inputs,neuron_weights):
        neuron=neuron+(n_input*weight)
    neuron+=neuron_bias
    layer.append(neuron)
print(layer)


[1.3, 5.1000000000000005, 2.21]


### What is tensor?

# Tensor is an object that can be represented as an array, tensor is not jsut an array

In [ ]:
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2

output=np.dot(weights,inputs)+bias

In [ ]:
output

In [ ]:
weights=[[0.2,0.8,-0.5,1.0],[0.5,0.91,0.26,-0.5],[0.26,-0.27,-0.17,0.87]]
bias=[1,3,0.5]
inputs=[1,2,3,4]
output=np.dot(weights,inputs)+bias

In [ ]:
output

##### Weight is the parameter within a neural network that transforms input data within the network's hidden layers

#### Batches,Layers and Objects

In [19]:
inputs=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]

weights=np.array([[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]])
bias=[2,3,0.5]
output=np.dot(inputs,weights.T)+bias
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [13]:
## Creating another layer
inputs=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]

weights=np.array([[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]])
bias=[2,3,0.5]

weights2=np.array([[0.1,-0.14,0.5],[-0.5,0.12,-0.33],[-0.44,0.73,-0.13]])
biases2=[-1,2,-0.5]

layer1_output=np.dot(inputs,weights.T)+bias

layer2_output=np.dot(layer1_output,weights2.T)+biases2

In [14]:
print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [20]:
x=[[1,2,3,2.5],
        [2,5,-1,2],
        [-1.5,2.7,3.3,-0.8]]   #we will assume that this is the input data to the neural netowk
np.random.seed(0)

# we are now going to define the hidden layers
# In case of a neural network there are two ways to intialise a layer.
# first is load the trianed model i.e just setting the right weight and biases whaterver is in the model
# Second create neural network from scratch
# Weights are intialised as random values in the rane -1 to 1 smaller the range better the result
# Biases we tend to intialise as zero but there are times when we dont want to do that
# becasue in some cases when neuron is not firing then some time if hte neuron is not able to give
# output then if we give zero then output will be zero which again given to another layer
# will give zero and if next neuron also gets zero that will propagate trhough entire network with zeros
# boom entire network is dead so in this we can start biases as non zero number

class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights=np.random.randn(n_inputs,n_neurons) # we want the shape that we need to pass in this case 
        #we need to know size of the input coming and how many neurons do we want to have size will be size o hte single sample in this case gonna pass a  batch
        # in this case it is 4
        # we want from numpy is to create weight that will be size of n inputs
        # multiplied by how many neurons do we want to have so well say n neurons
        # earlier shape was numebr of neurons by number of inputs but here it will it is numebr of inptus by nuber of neruons
        # the reason is because we if we do forward pass we dpnt need to give transpose everytime
        # that means we dont need to use transpose anymore
        
        self.biases=np.zeros((1,n_neurons))
        # shape is one by how many number of neurons we have
    def forward(self,inputs): # Forward will only take input 
#inputs will be actuall training data or input from the previous layer
        self.output=np.dot(inputs,self.weights)+self.biases
layer1= Layer_Dense(4,5)  # input is how many numeb of features in each sample
# 5 is any number you want
layer2=Layer_Dense(5,2) #input will be output of lahyer 1 which will be 5 because five neurons five outputs
# and output can be any shape

In [25]:
layer1.forward(x)
#print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[14.82959991 -8.39760189]
 [14.10031472 -1.3404687 ]
 [20.12497867 -7.29061598]]
